### ISSUE TITLE
Making the site mobile responsive

### ISSUE THREAD

**Issue by ankitk26** [PrathmeshSadake/unsplashy#10]
**Issue**: The site is not responsive on smaller screens.

- The masonry list of 3 columns makes the images difficult to see clearly.
- The search input has a smaller width and the navbar looks stacked.

<img src="https://user-images.githubusercontent.com/53444460/156204676-dd174285-6db5-4eed-809a-8e278afadf57.png" height="500" />

**Solution**
- Make the masonry list of 2 columns for smaller screens.
- Increase the width of the search input and align the items properly in the navbar.

Kindly assign me to fix this issue under GGSOC22

**Comment by mayank-del** [comment]
I have completed full stack development internship and  i made a page responsive which have only pixels in it's css, so, now i can make it responsive.

**Comment by nawed2611** [comment]
You can start working on it @ankitk26. !

**Comment by nawed2611** [comment]
Any updates? @ankitk26

**Comment by ankitk26** [comment]
It's almost done. Just the navbar is left to be made responsive. @nawed2611

**Comment by ankitk26** [comment]
I have already created the pull request

**Comment by nawed2611** [comment]
Ill review the PR

**Comment by roshanchatei** [comment]
If there is a problem then I would like to work on this issue

**Comment by roshanchatei** [comment]
@nawed2611 If there is a problem then I would like to work on this issue
