### ISSUE TITLE
Route Validation

### ISSUE THREAD

**Issue by Yourstruggle11** [PrathmeshSadake/unsplashy#16]
# Report Bug

# There is no route validation.

# If a user logs out and then goes to / home he is being given access to the home page again which should not be happen. instead of that he/she should be sent back to the login page

**Comment by shub78910** [comment]
I can work on this, could you assign this to me?

**Comment by Yourstruggle11** [comment]
@nawed2611 assign @shub78910 for this task

**Comment by nawed2611** [comment]
Hi, Please check out [this](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) to write clear and descriptive issues and writing in GitHub Markdown.

**Comment by shubham-Noustek** [comment]
> Hi, Please check out [this](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md) to write clear and descriptive issues and writing in GitHub Markdown.

Hi, I'm not sure, is this directed to me? (As I'm not documenting anything specific)

**Comment by roshanchatei** [comment]
@nawed2611 I would like to work on this issue.

**Comment by nawed2611** [comment]
Go ahead! @roshanchatei

**Comment by roshanchatei** [comment]
I have done route validation but why I am not able to push it
it's showing that I don't have access, @nawed2611 can you please help me out?

![unsplashy – Homepage js 3_31_2022 7_02_23 AM](https://user-images.githubusercontent.com/83601217/160958479-965221c0-376a-46f2-87ba-a43dc05a4637.png)

**Comment by roshanchatei** [comment]
> Hey @roshanchatei I believe you're trying to push directly to this repo. Did you clone your forked repo to the system? Try following [this](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/) and let me know if you're getting any issues

thanks a lot, I have resolved this issue.
