### ISSUE TITLE
Feature: Show/hide password while loggin in and signing up

### ISSUE THREAD

**Issue by Siddhesh777** [PrathmeshSadake/unsplashy#20]
### Feature description

Many times user wants to know that what password he/she has entered.
For this, there must be a functionality of toggling the view of password(show/hide).
We can achieve this using react hook useState.

I am contributor at gssoc'22.
Please assign this task to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by nawed2611** [comment]
Sure! @Siddhesh777

**Comment by Siddhesh777** [comment]
hey @nawed2611 
Can you assign this to me?😅

**Comment by nawed2611** [comment]
Done!
