### ISSUE TITLE
Feature: Add a Logo for Unsplashy website

### ISSUE THREAD

**Issue by shivam123-dev** [PrathmeshSadake/unsplashy#30]
### Feature description

There is no **LOGO** for the website.

![image](https://user-images.githubusercontent.com/81038095/161438994-511b523b-477a-418e-9eda-abfbf2ebc9a7.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by shivam123-dev** [comment]
I have designed the following logo for the website 

![logo](https://user-images.githubusercontent.com/81038095/161439060-08ed92d6-b33f-41d4-a648-0521eb6fa03b.png)

@nawed2611 can you please assign me this issue under GSSOC'22.

**Comment by nawed2611** [comment]
Sure!
