### ISSUE TITLE
Feature: Add Favicon

### ISSUE THREAD

**Issue by nawed2611** [PrathmeshSadake/unsplashy#33]
### Feature description

Currently, the project is using a sample React logo as the favicon for the project.

We want to add our own customized favicon for Unsplashy

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by roshanchatei** [comment]
@nawed2611 I would like to work on this issue
