### ISSUE TITLE
Navbar onScroll

### ISSUE THREAD

**Issue by roshanchatei** [PrathmeshSadake/unsplashy#35]
### Feature description

Generally, nowadays most websites have a non-elevated and transparent navbar but on scroll, it gets elevated and navbar background colour is changed.

### **Expected:**

**1. Before scroll**
![https___tralio-frontend-jczm0zj1y-saketharshraj vercel app - Brave 4_10_2022 9_32_30 PM](https://user-images.githubusercontent.com/83601217/162628850-13ed080a-3148-4a30-9563-52674eeb4b0e.png)

**2. After scroll**
![https___tralio-frontend-jczm0zj1y-saketharshraj vercel app - Brave 4_10_2022 9_32_39 PM](https://user-images.githubusercontent.com/83601217/162628856-19d930ec-1c0f-4127-952e-a1d0f7823f7c.png)

For more check, https://www.pexels.com/ just scroll and check the navbar

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by roshanchatei** [comment]
@nawed2611 Can you please add labels to this issue.
And I would like to work on this issue.

**Comment by nawed2611** [comment]
Go ahead! @roshanchatei

**Comment by roshanchatei** [comment]
@nawed2611 I think it's level 1 instead of level 0

**Comment by nawed2611** [comment]
i added the label in the PR
