### ISSUE TITLE
[Bug]: Duplicate of toggle password and one is not working

### ISSUE THREAD

**Issue by Olaleye-Blessing** [PrathmeshSadake/unsplashy#37]
### Contact Details

olayinkablexxy@gmail.com

### On Sign in and Sign Up page

There are duplicate show password options.

**Sign in page**

![Screenshot (352)](https://user-images.githubusercontent.com/70102539/163720509-4d581a25-8024-478b-89da-101e40aa629b.png)

Clicking the checkbox doesn't toggle the password

**Sign up page**

![Screenshot (353)](https://user-images.githubusercontent.com/70102539/163720543-4146fd83-97a1-484e-a733-61fd3727906c.png)

Clicking the eye icon doesn't toggle the password.

### What I expected
It'd be okay if there is just one option, either the checkbox or eye icon.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kanika637** [comment]
I would like to work on this issue under GSSoC 2022.

**Comment by nawed2611** [comment]
Go ahead! @Kanika637

**Comment by Kanika637** [comment]
I have made the PR, Kindly review it.

**Comment by nawed2611** [comment]
Great!
