### ISSUE TITLE
Home page text not properly visible

### ISSUE THREAD

**Issue by moulibrota-das** [PrathmeshSadake/unsplashy#4]
**The Issue:**
The text in the hero section of the home page is not properly visible if there is a dark colored picture in the background.

**Screenshot**
![image](https://user-images.githubusercontent.com/88196189/156011183-2d3fe9c0-ad04-4e13-8b08-bf25929f65e8.png)

**Comment by moulibrota-das** [comment]
Can you please assign me to this problem. Being a GSSOC'22 participant I can start working on it from March 1st.

**Comment by PrathmeshSadake** [comment]
Kindly start working to  fix this issue

**Comment by ashvin804** [comment]
can u assign this task to me.

**Comment by moulibrota-das** [comment]
### Issue Fixed 
Changed the Search Section Text Color and Added shadow for better visibility:

Addition changes (changed the class= to className=) in the SearchInput.js file :

```diff
-   <div class="wrap">
+  <div className="wrap">
```
After:

![Web capture_28-2-2022_213932_localhost](https://user-images.githubusercontent.com/88196189/156112090-ec5dd3ce-7804-4323-aca9-64006c127403.jpeg)
