### ISSUE TITLE
Carousel and Navbar improvement

### ISSUE THREAD

**Issue by unnikrishnan2002** [PrathmeshSadake/unsplashy#7]
Currently in the website the carousel is not in hundred percent of the screen . It would be great if we make the carousel to full screen and add two three more images to make the sliding animation. Also It would be good if the navbar is transparent and links with the picture and only becomes solid when someone scroll down.

**Comment by unnikrishnan2002** [comment]
@PrathmeshSadake I would like to work on this issue please - for GSSoC

**Comment by sulogna2001** [comment]
can I work on this issue under GSsoc22

**Comment by PrathmeshSadake** [comment]
@unnikrishnan2002 You can start working on this issue.

**Comment by PrathmeshSadake** [comment]
@sulogna2001 please visit https://unsplash.com to check if you can implement any feature in this project. Please update me about the feature I will guide you for the implementation process and also assign you the same.

**Comment by unnikrishnan2002** [comment]
> @unnikrishnan2002 You can start working on this issue.

Sure . Could you please add the level tag also

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by nawed2611** [comment]
Sure! @Abhilasha-Jairath

**Comment by roshanchatei** [comment]
@nawed2611 I would like to work on this issue and it would be better if we make this issue into two separate issues i.e. Carousel and Navbar

**Comment by roshanchatei** [comment]
@nawed2611 ??

**Comment by nawed2611** [comment]
Sure! Ill close this issue and you can create two different issues
